# Generated by Django 6.1.1 on 2026-09-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('total_frames', models.IntegerField(default=0)),
                ('completed_frames', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0)),
                ('output_file', models.CharField(blank=True, max_length=1000, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
